# Generated by Django 5.1.6 on 2025-02-07 19:13

import django.db.models.deletion
import rideshare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_rides',
            fields=[
                ('ride_id', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('female_only', models.BooleanField(default=False)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(default=rideshare.models.generate_random_id, max_length=20)),
                ('shared', models.BooleanField(default=False)),
                ('total_distance', models.FloatField(default=0)),
                ('total_cost', models.FloatField(default=0)),
                ('passenger_count', models.IntegerField(default=0)),
                ('passengers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('profile_pic', models.CharField(max_length=100)),
                ('chats', models.JSONField(default=list)),
                ('previous_rides', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.CharField(default=rideshare.models.generate_random_id, max_length=8, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('day_of_journey', models.CharField(max_length=50)),
                ('time_of_journey', models.TimeField()),
                ('female_only', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(default=0, max_length=50)),
                ('members', models.ManyToManyField(related_name='groups', to='rideshare.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('NOT_COMING', 'Not coming'), ('LATE_5', 'Late by 5 min'), ('LATE_10', 'Late by 10 min'), ('READY', 'Ready to go')], max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rideshare.groups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('cost', models.FloatField()),
                ('female_only', models.BooleanField(default=False)),
                ('shared', models.BooleanField(default=False)),
                ('ride_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rideshare.customer')),
            ],
        ),
    ]
